### PR TITLE
feat: support index in group().by

### PR DESCRIPTION
**Pull request by Himself65**
Fixes: #79

### CODE REVIEW

**Review by meyfa — CHANGES_REQUESTED** [review]
Thanks for the PR! Just two small requests:

1. Please fix the linting issues, this can be done automatically by running `npm run lint-fix` in your terminal.
2. I think we should update the README. At minimum, I imagine the item under "Usage" to change, where it currently says "`Provide a keying: .by('property') or .by(item => fn(item))`". It should say "`Provide a keying: .by('property') or .by((item, index) => fn(item, index))`".

**Comment by Himself65** [comment]
fixed

**Review by meyfa — APPROVED** [review]
Thanks, I'll go ahead and merge this!

**Comment by meyfa** [comment]
Released as v2.2.0 🎉

**Pull request merged**
